### ISSUE TITLE
v1.3.0 is doing BC breaks without a warning 

### ISSUE THREAD

**Issue by hyyan** [fxedel/toggle-icon#14]
@fxedel 

According to Semantic versioning 2.0.0

> Bug fixes not affecting the API increment is a patch version, backward compatible API additions/changes increment the minor version, and backward incompatible API changes increment the major version.

You have updated to polymer 2.x and released a minor version, which caused all our apps build to break now.
Updating to pure polymer 2.x element must be published in a major release 

I am using version `1.1.2` which is resolved now by bower to `1.3.0` as it must not break our apps , but it does.

Please consider solving this by releasing a new version and adding a warning in the changelog for version `1.3.01`

**Comment by GProst** [comment]
Guys, we have broken builds because of that too. Please fix 1.x version branch and create 2.x if you decided to go with Polymer 2.

**Comment by fxedel** [comment]
@hyyan @GProst I hope I've fixed it now: 1.4.0 is a revert to 1.2.1, whereas 2.0.0 adds the changes originally made in 1.3.0

**Comment by hyyan** [comment]
@fxedel That's great , Thanks a lot  😄 
I will close
