### ISSUE TITLE
Use "tap" event instead of "click"

### ISSUE THREAD

**Issue by avivien** [fxedel/toggle-icon#16]
Hi,

An improvement could be to use "tap" event instead of "click", it will allow a better behavior when use in mobile.
Thanks.

Regards,
Alexandre

**Comment by fxedel** [comment]
I actually have no issues using this component on my smart phone. Could you please further explain the differences / advantages?

Of course, you can always open a pull request to implement it on your own :wink:

**Comment by fxedel** [comment]
> In general, use the standard click event instead of tap in mobile browsers. The tap event is included in the gesture event mixin for backwards compatibility, but it's no longer required in modern mobile browsers. 

From the [Polymer documentation](https://polymer-library.polymer-project.org/3.0/docs/devguide/gesture-events). I don't think this issue is valid anymore ...

Feel free to add a comment if your opinion is different than mine!
