### ISSUE TITLE
Your component toggle-icon is featured in a Vaadin blog

### ISSUE THREAD

**Issue by binbalenci** [fxedel/toggle-icon#18]
Hi fxedel,

Just recently, I wrote the blog [Choose these toggling icon web components for your next project](https://vaadin.com/blog/wcw-14-toggling-icons) featuring toggle-icon. It got awesome animations and I like it a lot.

Feel free to drop a comment down below the comment section or in this [tweet](https://twitter.com/binhbbbb/status/1004283405616472065).

Cheers,
Binh

**Comment by fxedel** [comment]
Awesome, cool article! It's pretty encouraging for a developer like me to see people actually using the code I've written :)

**Comment by binbalenci** [comment]
@fxedel And the community has a big thank to you for making this component. Keep on rocking these web components 💪
