### ISSUE TITLE
Using IronCheckedElementBehavior would demand using the checked state

### ISSUE THREAD

**Issue by bastiion** [fxedel/toggle-icon#3]
In order to gain any  functionality from the `iron-checked-element-behavior` it would be necessary to
have a checked-property. If I want, for example, that an `on-iron-change` event is being fired to capture events in an dom-repeat template, there is no way of doing it in the current implementation.

So would it be an option to switch from `active` to `checked`?

**Comment by fxedel** [comment]
Thanks for your ideas! It shouldn't be a problem to rename the property. I'll test this in a few weeks – you could open a pull request in the meanwhile if you like to.

**Comment by fxedel** [comment]
Ok, now I'm working on it myself – no need to code it on your own and make a pr ;)
