### ISSUE TITLE
toggle-icon-0 toggle-icon-1 toggle-icon-2 toggle-icon-3

### ISSUE THREAD

**Issue by alexfromgalax87** [fxedel/toggle-icon#4]
Can you please tell me where this Classes are defined? Which file? Can't find it... :(

**Comment by fxedel** [comment]
Actually, I never defined them intentionally. Where did you find these names?

If you refer to id="..." or class=".." attributes: Maybe Polymer adds ids/classes with the element's name and it's index, so the first icon-toggle gets icon-toggle-0, the second icon-toggle-1 and the twenty-third one icon-toggle-22.
