### ISSUE TITLE
Changing version for 1.1

### ISSUE THREAD

**Issue by GeoloeG-IsT** [fxedel/toggle-icon#5]
Hi,
could you switch to a pure semver for the latest release, that is 1.1 => 1.1.0
It makes the update automatic for one of my component!
Thanks in advance,
Pascal

**Comment by fxedel** [comment]
Seems very easy, so I'll update the repo in a few minutes. Thanks for your issue, I didn't know that one should always specify the patch number of a version, although I do know http://semver.org/.
